### PR TITLE
Display output and errors from CMake when running in "server mode"

### PR DESCRIPTION
**Pull request by thorntonryan**
## Description

Modifies the `execute_process` command in `conan_cmake_install` to capture output and errors from Conan and reports it back to the user. Works even when CMake is in "server" mode.

## New Behavior

This pull modifies `conan_cmake_install` behavior to capture the output from `execute_process` in local variables, and then display that output back to the user via `message(STATUS ...)`.

This way, even when CMake is running in "server" mode, you see the output from the call to conan install in your IDE.

Worth noting, when calling CMake from a command line that owns stdout and stderr, the output will will be collected and reported all at once, i.e. it will no longer be streamed, which is a minor change in behavior.

However, this means `conan_cmake_install` behaves the same regardless of which mode ("server" or "non-server") CMake runs in.

## Current Behavior

When CMake is running in "server" mode, i.e. when launched from an IDE like QtCreator or Visual Studio, `conan_cmake_install` does not display any output or errors.

The output blocks on the call to `conan install`

If it fails, you see a non-descriptive error like this:
```
...
Conan ** WARNING** : This detection of settings from cmake is experimental and incomplete. Please check 'conan.cmake' and contribute
Detected VS runtime: MDd
Conan executing: conan install . -g cmake -s build_type=Debug -s os=Windows -s compiler=Visual Studio -s compiler.version=15 -s arch=x86 -s compiler.runtime=MDd --build=missing
CMake Error at C:/<path to>/conan.cmake:328 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  C:/<path to>/conan.cmake:405 (conan_cmake_install)
  CMakeLists.txt:90 (conan_cmake_run)


Configuring incomplete, errors occurred!
See also "C:/projects/build/myproject/CMakeFiles/CMakeOutput.log".
CMake Project parsing failed.
```
If it succeeds, you see no additional output (what packages were downloaded, what versions were resolved, if the package had to be built, etc.) from the call.

```
...
Conan executing: conan install . -g cmake -s build_type=Debug -s os=Windows -s compiler=Visual Studio -s compiler.version=15 -s arch=x86 -s compiler.runtime=MDd --build=missing
Conan: Loading conanbuildinfo.cmake
Current conanbuildinfo.cmake directory: C:/projects/build/myproject
Conan: Using cmake targets configuration
Library A found <pathtopackage>
Library B found <pathtopackage>
Library C found <pathtopackage>
...
```

## Reference

* [CMake Server announcement from Kitware](https://blog.kitware.com/cmake-e-server-improves-visual-studio-and-qt-creator-ides/)
* [CMake Support in Qt Creator (and elsewhere?)](http://blog.qt.io/blog/2016/11/15/cmake-support-in-qt-creator-and-elsewhere/)

### CODE REVIEW

**Comment by thorntonryan** [comment]
See also:
[execute_process doesn't print any output in Qt Creator - CMake #17931](https://gitlab.kitware.com/cmake/cmake/issues/17931)
[CMake: execute_process doesn't print any output - QTCREATORBUG-20162](https://bugreports.qt.io/browse/QTCREATORBUG-20162)

**Comment by memsharded** [comment]
Seems a good addition, thanks!

Could you please check what happens with the CLA? There might be some difference in the commit email and the github email, please check in the above link.

**Comment by thorntonryan** [comment]
> Could you please check what happens with the CLA? There might be some difference in the commit email and the github email, please check in the above link.

I apologize. I didn't catch the need for a CLA prior to submitting. I'm going through OSS review at the moment and hope to hear back from the legal group soon.

**Comment by memsharded** [comment]
Hi @thorntonryan 

Any update on this? I am preparing a new release of cmake-conan, would like to merge this if possible. If not, the code is fairly simple, you could close the PR, I will implement it myself. Thanks!

**Comment by thorntonryan** [comment]
@memsharded 

CLA approved and signed! Sorry for the delay. 

Thanks again for your patience and all your hard work on Conan!

**Comment by thorntonryan** [comment]
@memsharded , 

Let me know if there's anything else you'd like me to do. 

Thanks,
Ryan

**Comment by memsharded** [comment]
Merged, thanks for the contribution and sorry for the delays.
Will release it this week.

**Pull request merged**
