### PR TITLE
Add VS 17 2022 support

### PR DESCRIPTION
**Pull request by IceflowRE**

### CODE REVIEW

**Review by memsharded — COMMENTED** [review]
This is good, thanks.

The only problem is that Conan itself didn't implement built-in settings for this new version. The ticket is assigned for next release, but until then, this PR will not work yet.

**Comment by SSE4** [comment]
see also #9362
it should be a first step

**Review by SSE4 — APPROVED** [review]

**Comment by czoido** [comment]
Waiting for this PR https://github.com/conan-io/conan/pull/9370 to be merged and release in 1.40.
Adding to 0.17 milestone.

**Comment by maztheman** [comment]
I had to edit conan.conf to use Ninja to be the default generator to get conan to build the packages.

**Comment by f1nal3** [comment]
@czoido https://github.com/conan-io/conan/pull/9370 is mergerd and 1.40 is released

**Comment by czoido** [comment]
Merged now that Conan 1.40 was realeased

**Pull request merged**
