### PR TITLE
use stdlib clang flag to check libcxx

### PR DESCRIPTION
**Pull request by czoido**
When trying to detect the `libcxx` setting for conan if using clang you can set the `-stdlib` flag to `libc++` or `libdstdc++` but that was not being taken into account if the flag was set using `CMAKE_CXX_FLAGS` (but it was used if the flag was set with `add_compile_options`) 

Fixes: #229

### CODE REVIEW

**Comment by smessmer** [comment]
This should probably also set the `libcxx` variable in `PARENT_SCOPE`, see https://github.com/conan-io/cmake-conan/issues/256

**Comment by puetzk** [comment]
CMAKE_CXX_FLAGS is a string variable, not a ;-list. So you can't use foreach() on it directly, you have to deal with the shell quoting. And even that aside, I think the regex ought to be stricter, e.g. `if(cxx_flag MATCHES "(^| )-stdlib=")`? As is this could mismatch in the middle of some unrelated argument if e.g. a filename contained the word stdlib. c.f. how CMake itself derives this in CMakeDetermineCompilerId, though (unfortuntately) it only serializes it for Xcode projects, so you can't just use `${CLANG_CXX_LIBRARY}`.

https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/CMakeDetermineCompilerId.cmake#L508-516
https://gitlab.kitware.com/cmake/cmake/-/commit/8af334f5baa1a628895571491f67a4f7d9483d9b

But, conveniently, I actually think this whole PR is moot now that you accepted #197. It introduced using `separate_arguments` to parse `${CMAKE_CXX_FLAGS}` and passing the whole thing along to the `conan_cmake_detect_unix_libcxx` probing. So if there was a `-stdlib` in there you've already got it.

**Comment by czoido** [comment]
Hi @puetzk,
Thanks a lot for the comment, I think that's probably right, I'll do some tests and close the PR in that case.

**Comment by czoido** [comment]
This PR is no longer needed after the merge of #197.

**Pull request closed without merging**
