### PR TITLE
add PATHS ~/.local/bin

### PR DESCRIPTION
**Pull request by Sebanisu**
Default on ubuntu is to install conan into ~/.local/bin and cmake won't look there unless you give it a hint.

### CODE REVIEW

**Comment by Elnee** [comment]
Need it badly) I think that's why I have conan check error.

**Comment by Elnee** [comment]
@Sebanisu, according to this documentation maybe it's better to change `HINTS` to `PATHS`.

> Search the paths specified by the HINTS option. These should be paths computed by system introspection, such as a hint provided by the location of another item already found. Hard-coded guesses should be specified with the PATHS option.

Source: [find_program - CMake 3.22.0 Documentation](https://cmake.org/cmake/help/latest/command/find_program.html)

**Comment by czoido** [comment]
Hi @Sebanisu, @Elnee

You can set the [CONAN_COMMAND](https://github.com/conan-io/cmake-conan#conan_command) variable in your CMakeLists.txt for this:

```
set(CONAN_COMMAND "/usr/.local/bin/conan")
```

I'll close this, as that is the recommended way of setting a custom location for Conan, please feel free to reopen or open an issue if you have more comments or this does not work for you. Thanks a lot.

**Comment by Sebanisu** [comment]
I'm having no success with [CONAN_COMMAND](https://github.com/conan-io/cmake-conan#conan_command)  I also don't like hard coding the location of Conan when depending on the system it might be installed in a different place. `~/.local/bin/conan` is where pip installed it. I put that path in and it just failed to find it. It also caused the systems that were working to break.

**Comment by Sebanisu** [comment]
https://github.com/conan-io/cmake-conan/issues/32 there are some solutions in this issue.

**Pull request closed without merging**
