### PR TITLE
Support Android build with no toolchain

### PR DESCRIPTION
**Pull request by ssrobins**
This fixes the issues described in https://github.com/conan-io/cmake-conan/issues/563

### CODE REVIEW

**Comment by ssrobins** [comment]
@nmgwddj does this work for you?

**Comment by nmgwddj** [comment]
> #563

Yes, it solved my problem, thanks for spending your time on this.

**Comment by ssrobins** [comment]
@memsharded would it be possible to get a review of this please?

**Review by jcar87 — APPROVED** [review]
LGTM, thanks for your contribution!

**Pull request merged**
