### PR TITLE
Make configure_file COPYONLY (issue #160)

### PR DESCRIPTION
**Pull request by Morwenn**

### CODE REVIEW

**Comment by memsharded** [comment]
Good catch! Were you affected by some unfortunate variable substitution?
Thanks for contributing this

**Comment by Morwenn** [comment]
@memsharded Yes, my issue was explained in #160 :)

**Comment by memsharded** [comment]
Oh, great, didn't see it, thanks!

If you add in the first comment of this PR:

Close #160 

Close|closes|fix|fixes too, then the issue is automatically closed when the PR is merged :)

**Comment by Morwenn** [comment]
I use that in my own projects but tend not to do it for other people's projects just in case they want to accept the merge request but feel like there's more to do to fix the corresponding issue.

**Pull request merged**
