### PR TITLE
Add additional compiler options to conan_cmake_detect_unix_libcxx

### LINKED ISSUE #182: Automatic conan settings detection issue
## Summmary

There is an issue, when using `conan.cmake` in subdirectory, after `conan_basic_setup` is already invoked in parent project.

Below is the project structure:

```
/test-project
├── CMakeLists.txt
├── conanfile.py
└── sub-project
   ├── CMakeLists.txt
   └── conanfile.py
```

<details><summary>See CMake configure log</summary>
<p>

```log
-- The CXX compiler identification is GNU 9.2.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- COMPILE_OPTIONS= | COMPILE_DEFINITIONS= | /test-project
-- Downloading conan.cmake [v0.14] from https://github.com/conan-io/cmake-conan
-- Conan: checking conan executable in path
-- Conan: Found program /usr/bin/conan
-- Conan: Version found Conan version 1.18.4

-- Conan: Automatic detection of conan settings from cmake
-- Conan: Settings= -s;build_type=Release;-s;compiler=gcc;-s;compiler.version=9;-s;compiler.libcxx=libstdc++11
-- Conan executing: conan install /test-project/conanfile.py -s build_type=Release -s compiler=gcc -s compiler.version=9 -s compiler.libcxx=libstdc++11 -g=cmake -if=/test-project/cmake-build-test
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

conanfile.py (alice/0.1.1): Installing package
Requirements
Packages

conanfile.py (alice/0.1.1): Generator cmake created conanbuildinfo.cmake
conanfile.py (alice/0.1.1): Generator txt created conanbuildinfo.txt
conanfile.py (alice/0.1.1): Generated conaninfo.txt
conanfile.py (alice/0.1.1): Generated graphinfo
-- Conan: Loading conanbuildinfo.cmake
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Current conanbuildinfo.cmake directory: /test-project/cmake-build-test
-- Conan: Compiler GCC>=5, checking major version 9
-- Conan: Checking correct version: 9
-- COMPILE_OPTIONS=$<$<CONFIG:Debug>:>;$<$<CONFIG:Release>:>;$<$<CONFIG:RelWithDebInfo>:>;$<$<CONFIG:MinSizeRel>:> | COMPILE_DEFINITIONS= | /test-project
-- COMPILE_OPTIONS=$<$<CONFIG:Debug>:>;$<$<CONFIG:Release>:>;$<$<CONFIG:RelWithDebInfo>:>;$<$<CONFIG:MinSizeRel>:> | COMPILE_DEFINITIONS= | /test-project/sub-project
-- Downloading conan.cmake [v0.14] from https://github.com/conan-io/cmake-conan
-- Conan: checking conan executable in path
-- Conan: Found program /usr/bin/conan
-- Conan: Version found Conan version 1.18.4

-- Conan: Automatic detection of conan settings from cmake
c++: error: $<$<CONFIG:Debug>:>: No such file or directory
c++: error: $<$<CONFIG:Release>:>: No such file or directory
c++: error: $<$<CONFIG:RelWithDebInfo>:>: No such file or directory
c++: error: $<$<CONFIG:MinSizeRel>:>: No such file or directory
-- Conan: Settings= -s;build_type=Release;-s;compiler=gcc;-s;compiler.version=9;-s;compiler.libcxx=libc++
-- Conan executing: conan install /test-project/sub-project/conanfile.py -s build_type=Release -s compiler=gcc -s compiler.version=9 -s compiler.libcxx=libc++ -g=cmake -if=/test-project/cmake-build-test/sub-project
ERROR: Invalid setting 'libc++' is not a valid 'settings.compiler.libcxx' value.
Possible values are ['libstdc++', 'libstdc++11']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
CMake Error at cmake-build-test/sub-project/conan.cmake:399 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake-build-test/sub-project/conan.cmake:485 (conan_cmake_install)
  sub-project/CMakeLists.txt:43 (conan_cmake_run)


-- Configuring incomplete, errors occurred!
```

</p>
</details>

<details><summary>CMakeLists.txt (same in subdirectory)</summary>
<p>

```cmake
cmake_minimum_required(VERSION 3.8)

project(Alice
    VERSION 0.1.1
    LANGUAGES CXX
)


# DEBUG {{{
    get_directory_property(__co DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} COMPILE_OPTIONS)
    get_directory_property(__cd DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} COMPILE_DEFINITIONS)
    message(STATUS "COMPILE_OPTIONS=${__co} | COMPILE_DEFINITIONS=${__cd} | ${CMAKE_CURRENT_SOURCE_DIR}")
    unset(__co)
    unset(__cd)
# }}}

if (CONAN_EXPORTED)
    include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
    conan_basic_setup()
else(CONAN_EXPORTED)
    if(NOT CMAKE_CONAN_VERSION)
        set(CMAKE_CONAN_VERSION 0.14)
    endif(NOT CMAKE_CONAN_VERSION)

    # Download automatically, you can also just copy the conan.cmake file
    if(NOT EXISTS "${CMAKE_CURRENT_BINARY_DIR}/conan.cmake")
        message(STATUS "Downloading conan.cmake [v${CMAKE_CONAN_VERSION}] from https://github.com/conan-io/cmake-conan")
        file(DOWNLOAD "https://raw.githubusercontent.com/conan-io/cmake-conan/v${CMAKE_CONAN_VERSION}/conan.cmake"
            "${CMAKE_CURRENT_BINARY_DIR}/conan.cmake")
    endif()
    include(${CMAKE_CURRENT_BINARY_DIR}/conan.cmake)
    conan_check(REQUIRED)
    conan_cmake_run(CONANFILE conanfile.py BASIC_SETUP)
endif(CONAN_EXPORTED)


# DEBUG {{{
    get_directory_property(__co DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} COMPILE_OPTIONS)
    get_directory_property(__cd DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} COMPILE_DEFINITIONS)
    message(STATUS "COMPILE_OPTIONS=${__co} | COMPILE_DEFINITIONS=${__cd} | ${CMAKE_CURRENT_SOURCE_DIR}")
    unset(__co)
    unset(__cd)
# }}}

add_subdirectory(sub-project)
```

</p>
</details>

### Reason

After `conan_basic_setup` there are strange options populated via `COMPILE_OPTIONS` directory property: `COMPILE_OPTIONS=$<$<CONFIG:Debug>:>;$<$<CONFIG:Release>:>;$<$<CONFIG:RelWithDebInfo>:>;$<$<CONFIG:MinSizeRel>:>`

### Solution

Probably, it is issue in Conan CMake generator?
I can propose a quick fix to filter out such options when detecting settings.

### LINKED ISSUE #195: conan_cmake_detect_unix_libcxx fails with toolchains that require command-line arguments
If a unix toolchain requires command-line options to function (e.g. needs -m32/-m64, needs --sysroot, needs -B<prefix> to find an underlying cross-compiler), the invocation of `${CMAKE_CXX_COMPILER}` at https://github.com/conan-io/cmake-conan/blob/a0f8b138464ee5c8599056aceef2a695143c49f9/conan.cmake#L268 will not work, as it does not provide any of the flags even if they were set by the CMake toolchain file.

A similar problem would occur if using a wrapper script like `CC=ccache g++`, which would require using `${CMAKE_CXX_COMPILER_ARG1}`

I think this should include ``${CMAKE_CXX_FLAGS}`, or at bare minimum `${CMAKE_CXX_COMPILER_ARG1}` and `${CMAKE_CXX_COMPILER_ID_FLAGS_ALWAYS}` (though those are both really meant to be semi-private between the toolchain and CMakeDetermine<lang>Compiler).

But before diving into the intricacies of CMakeDetermineCXXCompiler and what needs to be passed, is there a reason this wasn't just done with [try_compile(OUTPUT_VARIABLE)](https://cmake.org/cmake/help/latest/command/try_compile.html)? It would seem like this could just write and try to build to build a source file that looked like 

    #ifdef __GLIBCXX__
        #if _GLIBCXX_USE_CXX11_ABI
            #warn libcxx=libstdc++11
        #else
            #warn libcxx=libstdc++
        #endif
    #ifdef _LIBCPP_VERSION
        #warn libcxx=libc++
    #else
        #error unknown libcxx
    #endif 

And then all the toolchain/cross-compiler/COMPILE_OPTIONS/COMPILE_DEFINITIONS stuff should just work itself out becuase CMake would actually use the same invocations it would use normally, and this could just look for the libcxx=... line in `${OUTPUT_VARIABLE}`

### PR DESCRIPTION
**Pull request by puetzk**
Without these many options many wrappers (e.g. ccache, winegcc) or cross-compiling toolchains (e.g. yocto) may not find the intended underlying tools and sysroot, leading to the command failing, or (perhaps worse) succeeding, but using defaults instead of the intended underlying gcc or libstdc++ and thus getting inaccurate results.

Fixes #182
Fixes #195

### CODE REVIEW

**Comment by puetzk** [comment]
one Travis failure (xcode8.3), but seems to be a network error hitting bintray, which seems unrelated to my changes:

https://travis-ci.org/conan-io/cmake-conan/jobs/641220956#L2958-L2961
> Hello/0.1@memsharded/testing: Not found in local cache, looking in remotes...
> Hello/0.1@memsharded/testing: Trying with 'conan-center'...
> ERROR: Failed requirement 'Hello/0.1@memsharded/testing' from 'Test/0.1@test/testing'
> ERROR: HTTPSConnectionPool(host='conan.bintray.com', port=443): Max retries exceeded with url: /v1/ping (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10615a438>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

I don't see a way to ask it to rerun; presumably that takes more permissions.

**Comment by czoido** [comment]
Hi @puetzk, I closed and opened to relaunch the CI

**Comment by puetzk** [comment]
Thanks. I've got the CLA submitted to our OSS governance contribution review;; I don't expect any problem since they've approved contributions in other Conan repositories with the same wording, but it's apparently taking a few days.

**Comment by puetzk** [comment]
CLA finally signed, sorry that took much longer than usual this time for some reason.

**Comment by smessmer** [comment]
Related issue that might touch on these changes: https://github.com/conan-io/cmake-conan/issues/256

**Review by memsharded — APPROVED** [review]

**Pull request merged**
