### PR TITLE
Tidy ups to variable and argument names

### PR DESCRIPTION
**Pull request by jhol**
This patch-set makes all variables and arguments consistent with `lower_case snake_case` style, ~with a underscore prefix applied to local variables~.

### CODE REVIEW

**Comment by valgur** [comment]
The `_` variable prefixes are unnecessary in `function`-s, since their scope is limited only to the function. I would keep them only for variables created inside `macro`-s, which do have a global scope.

**Comment by jhol** [comment]
> The `_` variable prefixes are unnecessary in `function`-s, since their scope is limited only to the function. I would keep them only for variables created inside `macro`-s, which do have a global scope.

Ok, no `_` variable prefixes in functions now, except where they are used as a shadows of output variables.

**Comment by jhol** [comment]
Can we have this merged?

**Comment by memsharded** [comment]
Hi @jhol 

The CI is red, this cannot be merged until it is green, could you please have a look?

**Comment by jhol** [comment]
> Hi @jhol
> 
> The CI is red, this cannot be merged until it is green, could you please have a look?

My mistake. I thought the test system was non-functional for this branch. The build issues should be fixed now.

**Comment by jhol** [comment]
This should be ready for merge now. Is there anything I can do to help get this accepted?

**Review by memsharded — APPROVED** [review]
Looks good to me, thanks for the contribution.

**Review by jcar87 — APPROVED** [review]

**Pull request merged**
