### PR TITLE
profile auto

### LINKED ISSUE #85: Profile argument causes error.
If PROFILE or related arguments are passed to `conan_cmake_run` or `conan_cmake_install`, cmake-conan ignores all settings, including `-g cmake`, which makes this option unuseable with CMake integration.

https://github.com/conan-io/cmake-conan/blob/36f25ff678cc32dd95caafe0acde9de34c0f1591/conan.cmake#L313

Following CMakeLists.txt is used with cmake-conan v0.11:
```cmake
cmake_minimum_required(VERSION 3.4)
project(test_cmake_conan)

set(BUILD_CONAN_MISSING FALSE CACHE BOOL "Build missing packages")
set(BUILD_CONAN_PROFILE "" CACHE STRING "Use profile to overide the profile detection")
set(BUILD_CONAN_UPDATE FALSE CACHE BOOL "Check updates exist from upstream remote")

list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/third_party/cmake")

include(conan)
if(BUILD_CONAN_MISSING)
    set(BUILD_CONAN_RULE "missing")
else()
    set(BUILD_CONAN_RULE "")
endif()

if(BUILD_CONAN_UPDATE)
    set(_BUILD_CONAN_UPDATE "UPDATE")
endif()

if(BUILD_CONAN_PROFILE)
    set(CONAN_DISABLE_CHECK_COMPILER True)
    set(_BUILD_CONAN_PROFILE PROFILE "${BUILD_CONAN_PROFILE}")
endif()

string(FIND "${CMAKE_BUILD_TYPE}" "Rel" REL_POS)
if(NOT(REL_POS LESS 0))
    set(_BUILD_CONAN_TYPE "Release")
else()
    set(_BUILD_CONAN_TYPE "Debug")
endif()

conan_cmake_run(
    CONANFILE conanfile.py
    BASIC_SETUP ${_BUILD_CONAN_UPDATE} CMAKE_TARGETS KEEP_RPATHS NO_OUTPUT_DIRS
    BUILD_TYPE ${_BUILD_CONAN_TYPE} ${_BUILD_CONAN_PROFILE}
    BUILD "${BUILD_CONAN_RULE}"
)
```

`cmake /path/to/project -DBUILD_CONAN_PROFILE=default` would print following errors:
```text
$ cmake /path/to/project -DBUILD_CONAN_PROFILE='default'
-- The C compiler identification is GNU 5.4.1
-- The CXX compiler identification is GNU 5.4.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan ** WARNING** : This detection of settings from cmake is experimental and incomplete. Please check 'conan.cmake' and contribute
-- Conan executing: conan install /path/to/project/conanfile.py -pr default
Version range '>=1.2.11-5' required by 'None' resolved to 'zlib/1.2.11@leebc/stable'
boost/1.64.0-2@leebc/stable requirement zlib/[>=1.2.11-0]@leebc/stable overriden by your conanfile to zlib/1.2.11@leebc/stable 
Version range '>=1.2.11-0' required by 'boost/1.64.0-2@leebc/stable' valid for downstream requirement 'zlib/1.2.11@leebc/stable'
PROJECT: Installing /path/to/project/conanfile.py
Requirements
    boost/1.64.0-2@leebc/stable from 'local'
    zlib/1.2.11-6@leebc/stable from 'local'
Packages
    boost/1.64.0-2@leebc/stable:c52c6fdfc799449191f9eace0697eb6daf7afb80
    zlib/1.2.11-6@leebc/stable:d358fec34c04bcd89832a09158783c750a3304dc

zlib/1.2.11-6@leebc/stable: Already installed!
boost/1.64.0-2@leebc/stable: Already installed!
boost/1.64.0-2@leebc/stable: LIBRARIES: ['boost_container', 'boost_iostreams', 'boost_program_options', 'boost_random', 'boost_regex', 'boost_thread', 'boost_chrono', 'boost_atomic', 'boost_filesystem', 'boost_system', 'rt', 'pthread']
boost/1.64.0-2@leebc/stable: Package folder: /home/leebc/.conan/data/boost/1.64.0-2/leebc/stable/package/c52c6fdfc799449191f9eace0697eb6daf7afb80
PROJECT: Generator txt created conanbuildinfo.txt
PROJECT: Generated conaninfo.txt
CMake Error at third_party/cmake/conan.cmake:381 (message):
  conanbuildinfo.cmake doesn't exist in
  /path/to/project/cmake-build-debug
Call Stack (most recent call first):
  third_party/cmake/conan.cmake:409 (conan_load_buildinfo)
  CMakeLists.txt:33 (conan_cmake_run)


-- Configuring incomplete, errors occurred!
See also "/path/to/project/cmake-build-debug/CMakeFiles/CMakeOutput.log".
```

### LINKED ISSUE #96: if BUILD_TYPE is specified, cmake generator should be used instead of cmake_multi
If the user has overridden the default `BUILD_TYPE`, script currently uses `cmake_multi` generator and two times installs the requested `build_type`, which then generates `cmake` configuration error because another `build_type` is missing (i.e. if the user has selected `Debug` build type, the user wants to use it in all configurations within its IDE and CMake throws error that `cmakebuildinfo_release.cmake` is missing).

[Here](https://github.com/microblink/conan-build-helper/blob/master/mb_conan_build.cmake#L136) is my dirty workaround for that issue from wrapper script that invokes your and performs additional setup specific for our internal build system.

### LINKED ISSUE #111: use major-only for Clang >= 8.0
Similar to https://github.com/conan-io/conan/pull/3643.
Instead of passing "compiler.version=${MAJOR}.${MINOR}" to the install command, "compiler.version=${MAJOR}" should be used if Clang >= 8.

### PR DESCRIPTION
**Pull request by memsharded**
This PR implements merging of info between the automatically deduce information from CMake and profiles:

- https://github.com/conan-io/cmake-conan/pull/98
- https://github.com/conan-io/cmake-conan/pull/87

The logic is to define argument PROFILE_AUTO=ARCH, COMPILER, BUILD_TYPE, COMPILER_VERSION.... These are the arguments that will be defined by cmake, overriding them if existing in profiles. It is necessary to introduce it to model the different use cases. Different users want different things: @dewhisna wants that profile and detected settings are always merged, while @bc-lee wants the profile override the detected settings, except for ``arch`` and ``build_type``.

Also close #111 
Also fix #96 
Also close #85

### CODE REVIEW

**Comment by puetzk** [comment]
For context I'm a co-worker of @dewhisna. This feels a little wordy, but it **is** nicely explicit. I think I like it.

I would have kept the setting keywords spelled exactly as in conan, though, install of uppercasing them; that would read more like the usual Cmake function(KEYWORD value1 value2) syntax, and cause fewer potential collisions between the keyword args and settings.yml keys (for example, you already have ARCH as a oneValueArgs, so conan_cmake_install (PROFILE_AUTO ARCH) won't actual parse they way I think you intend it (I think it will give an empty ARGUMENTS_PROFILE_AUTO, and an empty ARGUMENTS_ARCH)

I might also suggest that, if you did specify PROFILE_AUTO, it should no longer give the warning 
https://github.com/conan-io/cmake-conan/blob/61ae3b3356f2f2c6ca2a3dd0fedcc21a407bbe1c/conan.cmake#L70-L71

because it will have detected what you asked for, and you didn't want it to be complete anyway. Though I suppose for future-compatibility it should give a warning for unknown setting names (i.e. when _CONAN_SETTING_${ARG} is undefined rather than just falsey) when it loops through ARGUMENTS_PROFILE_AUTO, since that means you asked for something this version doesn't know how to detect.

https://github.com/conan-io/cmake-conan/blob/61ae3b3356f2f2c6ca2a3dd0fedcc21a407bbe1c/conan.cmake#L220-L221



at least if , .

**Comment by memsharded** [comment]
> I would have kept the setting keywords spelled exactly as in conan, though, install of uppercasing them; that would read more like the usual Cmake function(KEYWORD value1 value2) 

Yes, I think this is good, I will try to change it.

About the name collisions, I was wrong in the above example, but right in the code. CMake is case insensitive, so it doesn't matter to say ARCH or "arch", and it was colliding, so I had to define it as ``PROFILE_AUTO SETTINGS_ARCH``, ``PROFILE_AUTO SETTINGS_BUILD_TYPE``. I will try to change it to conan syntax: ``PROFILE_AUTO settings.arch`` and ``PROFILE_AUTO settings.compiler.version``, what do you think?

> I might also suggest that, if you did specify PROFILE_AUTO, it should no longer give the warning

I think maybe it is time to completely remove the warning. It is from earlier versions, where the detection was very un-mature. The detection of the settings is the main feature, and applies to the normal operation without specifying profiles, which is the most popular one for this conan.cmake project. Now it seems it is working reasonably well, so lets remove it.

Thanks for the feeback!

**Comment by bc-lee** [comment]
Using dots in the option (`dotted.lower.case`) is consistent with the conan settings syntax IMO, but it is a matter of preferences. Every other thing looks good to me.

**Comment by puetzk** [comment]
I don't have any problem with settings.arch, but cmake_parse_arguments **is** case-sensitive about its keywords:

```cmake
include (CMakeParseArguments)

cmake_parse_arguments(PREFIX1 "OPTION" "ONE_VALUE" "MULTI_VALUES" MULTI_VALUES OPTION)
cmake_parse_arguments(PREFIX2 "OPTION" "ONE_VALUE" "MULTI_VALUES" MULTI_VALUES option)

message("PREFIX1_OPTION=${PREFIX1_OPTION}")
message("PREFIX1_MULTI_VALUES=${PREFIX1_MULTI_VALUES}")

message("PREFIX2_OPTION=${PREFIX2_OPTION}")
message("PREFIX2_MULTI_VALUES=${PREFIX2_MULTI_VALUES}")
```

prints

```
PREFIX1_OPTION=TRUE
PREFIX1_MULTI_VALUES=
PREFIX2_OPTION=FALSE
PREFIX2_MULTI_VALUES=option
```

Tested in 2.8.12 and 3.12

**Comment by memsharded** [comment]
Excellent @puetzk 
I didn't know cmake was case-sensitive regarding arguments. So I removed ``settings.`` prefix, it is much cleaner. Thanks for the feedback!

**Comment by puetzk** [comment]
It might make sense for PROFILE_AUTO to also accept something like `PROFILE_AUTO "*"` or `PROFILE_AUTO all` or something of that sort. This would make it easier to get the behavior #98 asked for (start with the named profile as default, and then override it with as much detection as possible), though still explicitly asking for it to distinguish this from #87's request. It feels like there ought to be some way to get the same behavior as when using using `[general]default_profile` or `$ENV{CONAN_DEFAULT_PROFILE_PATH}`, just with the cmake caller providing the starting profile name.

Implementing this would just be expanding "*" or "all" (or whatever keyword you want to use) into the same list you have for when there's no PROFILE keyword given, i.e.

https://github.com/conan-io/cmake-conan/blob/6320eb20eb0543b1724cd0cfe05980f774f6c3eb/conan.cmake#L199-L201

**Pull request merged**
