### PR TITLE
Add --conf arguments for `conan install` command.

### PR DESCRIPTION
**Pull request by hwhsu1231**
Add the following arguments of [`conan install`](https://docs.conan.io/en/latest/reference/commands/consumer/install.html) command:

- `--conf`
- `--conf:host`
- `--conf:build`

for `conan_cmake_install()` function.

### CODE REVIEW

**Comment by hwhsu1231** [comment]
Hello @memsharded or @czoido,

Recently, I found an **ALTERNATIVE** way to use `cmake-conan`, which can successfully use `CMakeToolchain` generator. However, I met a problem which need to add the following argument in `conan install` command:

```cmd
--conf tools.cmake.cmaketoolchain:generator="Ninja Multi-Config"
```

Therefore, I posted this PR to add `CONF`, `CONF_HOST`, and `CONF_BUILD` arguments for `conan_cmake_install()` function. Can you check whether this PR can be merged? Thanks a lot!

**Comment by czoido** [comment]
Hi @hwhsu1231,
Thanks a lot for contributing this, it's looking good, let's check if the ci passes. Did you tests it locally? Adding at least one test would be nice.

**Comment by hwhsu1231** [comment]
Yes. I prepared a modified `conan.cmake` locally and copied it to the build directory instead of downloading from the repository.  And it worked as I expected.

image

**Comment by hwhsu1231** [comment]
@czoido Execuse me. What do you mean **"Adding at least one test would be nice."**? Where do I need to add the test? What kind of test should I add?

**Comment by czoido** [comment]
> @czoido Execuse me. What do you mean **"Adding at least one test would be nice."**? Where do I need to add the test? What kind of test should I add?

I meant adding it here: https://github.com/conan-io/cmake-conan/blob/develop/tests.py but don't worry about that, I'll update the branch with a test.

**Comment by hwhsu1231** [comment]
@czoido Recently, I'm trying an alternatvie way to use cmake-conan. And this argument `--conf` is necessary for CMakeToolchain to generate a proper `conan_toolchain.cmake`. Hope this PR can be merged as soon as possible.

**Comment by czoido** [comment]
Hi @hwhsu1231,
I have just pushed a test for this feature, it will be merged for 0.19 release as soon as the ci passes.

**Pull request merged**
