### PR TITLE
Allow setting arch to conan_cmake_settings

### PR DESCRIPTION
**Pull request by bc-lee**
Fixes: #68

### CODE REVIEW

**Comment by memsharded** [comment]
Is this a duplicate of https://github.com/conan-io/cmake-conan/pull/69?

**Comment by bc-lee** [comment]
No, it was my mistake and a modified commit has been added to this pull request.

**Comment by bc-lee** [comment]
Seems like the package [Hello/0.1@memsharded/testing](https://github.com/memsharded/hello) that is used in tests are not elegible to build 32bit-binaries in 64bit Linux..

A quick and dirty solution for patching `conanfile.py` using  AutoToolsBuildEnvironment is follows:

    diff --git a/conanfile.py b/conanfile.py
    index 3a45fc4..693b309 100644
    --- a/conanfile.py
    +++ b/conanfile.py
    @@ -1,4 +1,4 @@
    -from conans import ConanFile, CMake
    +from conans import ConanFile, CMake, AutoToolsBuildEnvironment, tools
        
     class HelloConan(ConanFile):
         name = "Hello"
    @@ -11,9 +11,11 @@ class HelloConan(ConanFile):
             self.run("git clone https://github.com/memsharded/hello.git")
     
         def build(self):
    -        cmake = CMake(self)
    -        self.run('cd hello && cmake . %s' % cmake.command_line)
    -        self.run("cd hello && cmake --build . %s" % cmake.build_config)
    +        autotools = AutoToolsBuildEnvironment(self)
    +        with tools.environment_append(autotools.vars):
    +            cmake = CMake(self)
    +            self.run('cd hello && cmake . %s' % cmake.command_line)
    +            self.run("cd hello && cmake --build . %s" % cmake.build_config)
     
         def package(self):
             self.copy("*.h", dst="include", src="hello")

**Comment by memsharded** [comment]
Thanks for contributing this!
I will try to add a conditional test or something for the next release.

**Pull request merged**
