### PR TITLE
Additional ways to override settings

### PR DESCRIPTION
**Pull request by r4zzz4k**
This PR contains two changes:
* Ability to set profiles for `RelWithDebInfo` and `MinSizeRel` build types in similar way to https://github.com/conan-io/cmake-conan/pull/46 -- this seems like a natural extension of that PR.
* Ability to pass custom `-s` flags to Conan via `SETTINGS` argument of `conan_cmake_run`. I see two reasons to have this in:
    * One could have custom CMake build step;
    * One could wish to configure conan entirely via CMake without need for other files like profile definitions.

### CODE REVIEW

**Comment by memsharded** [comment]
Looks very good, thank you!

Could you please try to add some tests for these new features? Tell me if you need help, or can't manage, and I will try to help or add the tests myself. Thanks!

**Comment by martin-schulze-vireso** [comment]
@memsharded I urgently need this PR and there has been no progress for over a month now. What needs to be done in these tests?

Should the tests make sure that there is a change or that the change is effective e.g.:
- RelWithDebInfo checks that the binary has debug symbols
- MinSizeRel checks that the binary got smaller
- custom settings checks that the custom setting is used in the requested packages

The tests so far seem to be much more "shallow" in that regard. If we know what needs to by done, I would be willing to contribute.

**Comment by memsharded** [comment]
No problem.

Added one test in: https://github.com/conan-io/cmake-conan/pull/80, passing CI, will release 0.10 when finished.

**Comment by memsharded** [comment]
And here we go @martin-schulze-vireso https://github.com/conan-io/cmake-conan/releases/tag/v0.10

Cheers!

**Comment by martin-schulze-vireso** [comment]
Wow, thanks for the swift response @memsharded

**Comment by r4zzz4k** [comment]
I'm sorry, got lost with my current project which is unfortunately unrelated to Conan. Great job, @memsharded! I actually tried to come up with tests at that time but failed, that's why there were no news from me. Sorry for radio silence!

**Comment by memsharded** [comment]
Ey @r4zzz4k no worries and no apologies! Thanks for your contribution, we are here to try to support these cases, we are willing to help as much as possible. We are also very busy ourselves, so we understand, don't hesitate to ask for help when necessary. Many thanks!

**Pull request merged**
