### PR TITLE
Conan config install

### PR DESCRIPTION
**Pull request by goranbrkic**
Implements https://github.com/conan-io/cmake-conan/issues/151

Add conan_config_install macro
Add test for conan_config_install macro
Update README.md for conan_config_install macro

### CODE REVIEW

**Comment by memsharded** [comment]
Hi @goranbrkic 

I have fired again CI (failed because of network, not because the PR), and solved merge conflicts, it is looking good to be merged, thanks!

Please check the CLA above, if not green it could be that you used a different email for your commits than the one you use for your github account. The link above should help to solve it.

**Comment by goranbrkic** [comment]
Hi @memsharded 

Is there any additional step required for this PR to be merged?

**Comment by megabyde** [comment]
@memsharded any updates on this?

**Comment by memsharded** [comment]
Merged, lets try to release 0.15 soon.

**Pull request merged**
