### PR TITLE
Fix location of conanbuildinfo.cmake (#88)

### PR DESCRIPTION
**Pull request by tofferlicious**
In case ARGUMENTS_INSTALL_FOLDER is set, the location of conanbuildinfo.cmake will be loaded from it with this commit.

Otherwise the method call will fail with an error as described in https://github.com/conan-io/cmake-conan/issues/88

### CODE REVIEW

**Comment by tofferlicious** [comment]
It seems like a server is not reachable from the build environments running the tests:
ERROR: Error 502 downloading file https://api.bintray.com/conan/conan/conan-transit/v1/files/memsharded/Hello/0.1/testing/export/conanmanifest.txt

But the file is downloadable for me...

**Comment by memsharded** [comment]
Hi @tofferlicious 

Sorry for the delay. I think this has also been fixed in https://github.com/conan-io/cmake-conan/pull/135, merged to develop. It will be released soon in 0.14, could you please check to make sure? Thanks

**Comment by tofferlicious** [comment]
Hi @memsharded,

Thanks for getting back on this.
Works like a charme :+1:

**Comment by memsharded** [comment]
Great, thanks for the feedback!

**Pull request merged**
